---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-1729853058895
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-1729853058895 
  name: chatbot-1729853058895
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi